"""test

Revision ID: 9158f3b0fd11
Revises: 
Create Date: 2026-04-19 20:46:05.977225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9158f3b0fd11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_long', sa.Float(), nullable=True),
    sa.Column('town_city', sa.String(length=100), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('contact_person_name', sa.String(length=100), nullable=False),
    sa.Column('contact_person_phone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_companies_company_id'), 'companies', ['company_id'], unique=False)
    op.create_table('staff',
    sa.Column('staff_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('lecturer', 'coordinator', name='staffrole'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('staff_id')
    )
    op.create_index(op.f('ix_staff_email'), 'staff', ['email'], unique=True)
    op.create_index(op.f('ix_staff_staff_id'), 'staff', ['staff_id'], unique=False)
    op.create_table('students',
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('staff_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ),
    sa.PrimaryKeyConstraint('reg_no')
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_reg_no'), 'students', ['reg_no'], unique=False)
    op.create_table('final_reports',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=True),
    sa.Column('report_file_upload', sa.String(length=500), nullable=True),
    sa.Column('completion_status', sa.Enum('pending', 'submitted', 'graded', 'completed', name='completionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reg_no'], ['students.reg_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('reg_no')
    )
    op.create_index(op.f('ix_final_reports_report_id'), 'final_reports', ['report_id'], unique=False)
    op.create_table('placements',
    sa.Column('placement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reg_no'], ['students.reg_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('placement_id')
    )
    op.create_index(op.f('ix_placements_placement_id'), 'placements', ['placement_id'], unique=False)
    op.create_table('field_visits',
    sa.Column('visit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('reg_no', sa.String(length=50), nullable=False),
    sa.Column('staff_id', sa.String(length=50), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('visit_form_upload', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.placement_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reg_no'], ['students.reg_no'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.staff_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('visit_id')
    )
    op.create_index(op.f('ix_field_visits_visit_id'), 'field_visits', ['visit_id'], unique=False)
    op.create_table('weekly_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('placement_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('week_no', sa.Integer(), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=False),
    sa.Column('logbook_file_upload', sa.String(length=500), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('station_supervisor_name', sa.String(length=100), nullable=False),
    sa.Column('station_supervisor_phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'reviewed', 'missing', name='logstatus'), nullable=False),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['placement_id'], ['placements.placement_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_weekly_logs_log_id'), 'weekly_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_logs_log_id'), table_name='weekly_logs')
    op.drop_table('weekly_logs')
    op.drop_index(op.f('ix_field_visits_visit_id'), table_name='field_visits')
    op.drop_table('field_visits')
    op.drop_index(op.f('ix_placements_placement_id'), table_name='placements')
    op.drop_table('placements')
    op.drop_index(op.f('ix_final_reports_report_id'), table_name='final_reports')
    op.drop_table('final_reports')
    op.drop_index(op.f('ix_students_reg_no'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_staff_staff_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_email'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_companies_company_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
